# Generated by Django 5.2.5 on 2025-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(help_text='Nama icon lucide/react atau fontawesome', max_length=100)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='fasilitas/')),
            ],
        ),
    ]
