# Generated by Django 5.2.5 on 2025-08-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='galeri/')),
                ('jenis', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], default='foto', max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
