# Generated by Django 5.2.5 on 2025-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
    ]
